// <auto-generated />
using System;
using CodeFirstMusicSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstMusicSystem.Migrations
{
    [DbContext(typeof(MusicSystemContext))]
    [Migration("20230323021343_podcastandTrackNumber")]
    partial class podcastandTrackNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("GuestArtistId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GuestArtistId");

                    b.HasIndex("PodcastId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.GuestArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GuestArtists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.GuestArtistEpisode", b =>
                {
                    b.Property<int>("GuestArtistId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("GuestArtistId", "EpisodeId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("GuestArtistEpisodes");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.ListenerList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddListenerListViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PodcastId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddListenerListViewModelId");

                    b.HasIndex("PodcastId");

                    b.ToTable("ListenerList");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PlaylistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddListenerListViewModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddListenerListViewModelId");

                    b.ToTable("Podcast");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastArtist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PodcastArtists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastCastArtist", b =>
                {
                    b.Property<int>("PodcastArtistId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PodcastArtistId", "PodcastId");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastCastArtists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastListenerList", b =>
                {
                    b.Property<int>("ListenerListId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ListenerListId", "PodcastId");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastListenerLists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrackSong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.SongContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("SongContributor");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Viewmodel.AddListenerListViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ListenerListId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AddListenerListViewModel");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Album", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Artist", null)
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Episode", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.GuestArtist", null)
                        .WithMany("Episodes")
                        .HasForeignKey("GuestArtistId");

                    b.HasOne("CodeFirstMusicSystem.Models.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.GuestArtistEpisode", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Episode", "Episode")
                        .WithMany("GuestArtistEpisodes")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstMusicSystem.Models.GuestArtist", "GuestArtist")
                        .WithMany()
                        .HasForeignKey("GuestArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("GuestArtist");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.ListenerList", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Viewmodel.AddListenerListViewModel", null)
                        .WithMany("ListenerLists")
                        .HasForeignKey("AddListenerListViewModelId");

                    b.HasOne("CodeFirstMusicSystem.Models.Podcast", null)
                        .WithMany("ListenerLists")
                        .HasForeignKey("PodcastId");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PlaylistSong", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstMusicSystem.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Podcast", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Viewmodel.AddListenerListViewModel", null)
                        .WithMany("Podcasts")
                        .HasForeignKey("AddListenerListViewModelId");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastCastArtist", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.PodcastArtist", "PodcastArtist")
                        .WithMany("PodcastCastArtists")
                        .HasForeignKey("PodcastArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstMusicSystem.Models.Podcast", "Podcast")
                        .WithMany("PodcastCastArtists")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");

                    b.Navigation("PodcastArtist");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastListenerList", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.ListenerList", "ListenerList")
                        .WithMany("ListenerListPodcasts")
                        .HasForeignKey("ListenerListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstMusicSystem.Models.Podcast", "Podcast")
                        .WithMany()
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListenerList");

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Song", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.SongContributor", b =>
                {
                    b.HasOne("CodeFirstMusicSystem.Models.Artist", "Artist")
                        .WithMany("SongContributors")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstMusicSystem.Models.Song", "Song")
                        .WithMany("SongContributors")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("SongContributors");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Episode", b =>
                {
                    b.Navigation("GuestArtistEpisodes");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.GuestArtist", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.ListenerList", b =>
                {
                    b.Navigation("ListenerListPodcasts");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Podcast", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("ListenerLists");

                    b.Navigation("PodcastCastArtists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.PodcastArtist", b =>
                {
                    b.Navigation("PodcastCastArtists");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Song", b =>
                {
                    b.Navigation("PlaylistSongs");

                    b.Navigation("SongContributors");
                });

            modelBuilder.Entity("CodeFirstMusicSystem.Models.Viewmodel.AddListenerListViewModel", b =>
                {
                    b.Navigation("ListenerLists");

                    b.Navigation("Podcasts");
                });
#pragma warning restore 612, 618
        }
    }
}
